[package]
name = "pulsedoc"
version = "0.0.2"
edition = "2024"

[dependencies]
chrono = "0.4.43"
inquire = "0.9.1"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.149"
docx-handlebars = "0.3"
rfd = "0.17.2"
